/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package site.caoh.exe;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TradeCMD implements org.apache.thrift.TEnum {
  OP_BUY_LIMIT(2),
  OP_SELL_LIMIT(3),
  OP_BUY_STOP(4),
  OP_SELL_STOP(5);

  private final int value;

  private TradeCMD(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TradeCMD findByValue(int value) { 
    switch (value) {
      case 2:
        return OP_BUY_LIMIT;
      case 3:
        return OP_SELL_LIMIT;
      case 4:
        return OP_BUY_STOP;
      case 5:
        return OP_SELL_STOP;
      default:
        return null;
    }
  }
}
